import { createServerFn } from "@tanstack/react-start";

export const getAdminData = createServerFn({ method: "POST" })
  .handler(async () => {
    return {
      pages: [
        {
          id: "page-1",
          slug: "team",
          label_en: "Our Team",
          label_es: "Nuestro Equipo",
          title_en: "Our Team",
          title_es: "Nuestro Equipo",
          body_en: "Our team content...",
          body_es: "Contenido del equipo...",
          image: "/team.jpg",
          sort_order: 1,
          visible: true,
          is_system: true,
        },
        {
          id: "page-2",
          slug: "about",
          label_en: "About Us",
          label_es: "Sobre Nosotros",
          title_en: "About Us",
          title_es: "Sobre Nosotros",
          body_en: "About us content...",
          body_es: "Contenido sobre nosotros...",
          image: "/about.jpg",
          sort_order: 2,
          visible: true,
          is_system: false,
        },
      ],
      dropoffs: [
        {
          id: "dropoff-1",
          name: "Roma Spaghetti",
          address: "Calle 34, entre 5ta y 10ma Av",
          hours_en: "Mon-Sat 12pm-10pm",
          hours_es: "Lun-Sáb 12pm-10pm",
          phone: "+52 984 111 2222",
          map_url: "https://maps.google.com/?q=Roma+Spaghetti+Playa+del+Carmen",
          image: "",
          sort_order: 1,
          visible: true,
        },
        {
          id: "dropoff-2",
          name: "Pueblito Escondido Calle 38",
          address: "Calle 38, entre 5ta y 10ma Av",
          hours_en: "Daily 8am-10pm",
          hours_es: "Diario 8am-10pm",
          phone: "+52 984 333 4444",
          map_url: "https://maps.google.com/?q=Pueblito+Escondido+Calle+38+Playa+del+Carmen",
          image: "",
          sort_order: 2,
          visible: true,
        },
      ],
      volunteerNeeds: [
        {
          id: "volunteer-1",
          title_en: "Food Packing",
          title_es: "Empaque de Alimentos",
          desc_en: "Help assemble weekly despensas every Tuesday morning.",
          desc_es: "Ayuda a armar despensas semanales cada martes por la mañana.",
          image: "",
          sort_order: 1,
          visible: true,
        },
        {
          id: "volunteer-2",
          title_en: "Garden Sales",
          title_es: "Ventas de Huerto",
          desc_en: "Run the weekend plant/veggie sale to raise funds.",
          desc_es: "Organiza la venta de plantas/verduras del fin de semana para recaudar fondos.",
          image: "",
          sort_order: 2,
          visible: true,
        },
      ],
      donationMethods: [
        {
          id: "1",
          name_en: "Stripe",
          name_es: "Stripe",
          details_en: "Credit/Debit Card (Stripe). One-time or monthly.",
          details_es: "Tarjeta de Crédito/Débito (Stripe). Único o mensual.",
          link: "https://buy.stripe.com/00g7sy5O9aJRgdafYY",
          qr: "/QR-stripe-donate.webp",
          image: "",
          visible: true,
          sort_order: 1,
        },
        {
          id: "2",
          name_en: "PayPal (USA & Canada tax-deductible)",
          name_es: "PayPal (deducible de impuestos en USA y Canadá)",
          details_en: "USA & Canada tax-deductible receipts available.",
          details_es: "Recibos deducibles de impuestos en USA y Canadá disponibles.",
          link: "https://www.paypal.com/ncp/payment/5DS8TXGHLDVL2",
          qr: "/QR-USA-and-Canada-Tax-Purposes.webp",
          image: "",
          visible: true,
          sort_order: 2,
        },
        {
          id: "3",
          name_en: "OXXO (Mexico)",
          name_es: "OXXO (México)",
          details_en: "Pay cash at any OXXO in Mexico. Reference: BOL",
          details_es: "Paga en efectivo en cualquier OXXO en México. Referencia: BOL",
          link: "",
          qr: "",
          image: "",
          visible: true,
          sort_order: 3,
        },
        {
          id: "4",
          name_en: "Banco Azteca",
          name_es: "Banco Azteca",
          details_en: "Michele Avila Mendoza | Card: 4027 6661 1819 3043 | CLABE: 127694013013508192",
          details_es: "Michele Avila Mendoza | Tarjeta: 4027 6661 1819 3043 | CLABE: 127694013013508192",
          link: "",
          qr: "",
          image: "",
          visible: true,
          sort_order: 4,
        },
        {
          id: "5",
          name_en: "Mercado Pago W",
          name_es: "Mercado Pago W",
          details_en: "Michele Avila Mendoza | CLABE: 722969010176925651",
          details_es: "Michele Avila Mendoza | CLABE: 722969010176925651",
          link: "",
          qr: "",
          image: "",
          visible: true,
          sort_order: 5,
        },
      ],
      pages: [
        {
          id: "page-1",
          slug: "team",
          label_en: "Our Team",
          label_es: "Nuestro Equipo",
          title_en: "Our Team",
          title_es: "Nuestro Equipo",
          body_en: "Our team content...",
          body_es: "Contenido del equipo...",
          image: "/team.jpg",
          sort_order: 1,
          visible: true,
          is_system: true,
        },
        {
          id: "page-2",
          slug: "about",
          label_en: "About Us",
          label_es: "Sobre Nosotros",
          title_en: "About Us",
          title_es: "Sobre Nosotros",
          body_en: "About us content...",
          body_es: "Contenido sobre nosotros...",
          image: "/about.jpg",
          sort_order: 1,
          visible: true,
          is_system: false,
        },
      ],
      contentBlocks: {
        donate_intro: {
          en: "Monetary Donations: STRIPE: https://buy.stripe.com/00g7sy5O9aJRgdafYY | PAYPAL: axansolustra@gmail.com | OXXO or Mexican Bank: Banco Azteca (Michele Avila Mendoza, Card: 4027 6661 1819 3043, CLABE: 127694013013508192) | Mercado Pago W (CLABE: 722969010176925651). Reference: BOL. Cash accepted at drop-off locations.",
          es: "Donaciones Monetarias: STRIPE: https://buy.stripe.com/00g7sy5O9aJRgdafYY | PAYPAL: axansolustra@gmail.com | OXXO o Depósito Bancario Mexicano: Banco Azteca (Michele Avila Mendoza, Tarjeta: 4027 6661 1819 3043, CLABE: 127694013013508192) | Mercado Pago W (CLABE: 722969010176925651). Referencia: BOL. Aceptamos efectivo en puntos de entrega."
        },
      },
    };
  },
};