/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DropOffRouteImport } from './routes/drop-off'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ValuesRouteImport } from './routes/values'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DropOffRoute = DropOffRouteImport.update({
  id: '/drop-off',
  path: '/drop-off',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuesRoute = ValuesRouteImport.update({
  id: '/values',
  path: '/values',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/drop-off': typeof DropOffRoute
  '/help': typeof HelpRoute
  '/values': typeof ValuesRoute
  '/volunteer': typeof VolunteerRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/drop-off': typeof DropOffRoute
  '/help': typeof HelpRoute
  '/values': typeof ValuesRoute
  '/volunteer': typeof VolunteerRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/drop-off': typeof DropOffRoute
  '/help': typeof HelpRoute
  '/values': typeof ValuesRoute
  '/volunteer': typeof VolunteerRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/donate'
    | '/drop-off'
    | '/help'
    | '/values'
    | '/volunteer'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/donate'
    | '/drop-off'
    | '/help'
    | '/values'
    | '/volunteer'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/donate'
    | '/drop-off'
    | '/help'
    | '/values'
    | '/volunteer'
    | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  DropOffRoute: typeof DropOffRoute
  HelpRoute: typeof HelpRoute
  ValuesRoute: typeof ValuesRoute
  VolunteerRoute: typeof VolunteerRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop-off': {
      id: '/drop-off'
      path: '/drop-off'
      fullPath: '/drop-off'
      preLoaderRoute: typeof DropOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/values': {
      id: '/values'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof ValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  DropOffRoute: DropOffRoute,
  HelpRoute: HelpRoute,
  ValuesRoute: ValuesRoute,
  VolunteerRoute: VolunteerRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
