// This file is automatically generated. Do not edit it directly.

// Simple auth storage using localStorage for production
export function brokeredPreviewStorage() {
  if (typeof window === "undefined") return undefined;
  return localStorage;
}
